---
  - name: Add grafana repo
    yum_repository:
      name: grafana
      description: grafana server
      baseurl: https://packages.grafana.com/oss/rpm
      gpgcheck: yes
      gpgkey: https://packages.grafana.com/gpg.key
      state: present

  - name: Install grafana
    dnf:
      name: grafana
      state: present

  - name: Copy configuration file
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
    notify:
      - grafana_restart

  - name: Copy datasource
    template:
      src: datasource.yml.j2
      dest: /etc/grafana/provisioning/datasources/default.yaml
    notify:
      - grafana_restart

  - name: Copy dashboard config
    template:
      src: dashboard.yml.j2
      dest: /etc/grafana/provisioning/dashboards/default.yaml
    notify:
      - grafana_restart

  - name: Copy dashboard
    copy:
      src: dashboard.json
      dest: /etc/grafana/provisioning/dashboards/

  - name: Enable and start grafana
    service:
      name: grafana-server
      state: started
      enabled: yes

