---
  - name: Add Prometheus repo
    yum_repository:
      name: prometheus
      description: prometheus
      baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
      gpgcheck: yes
      gpgkey: https://packages.grafana.com/gpg.key
      state: present

  - name: Install Prometheus
    dnf:
      name: grafana
      state: present

  - name: Enable and start Prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
