---
  - name: Enable EPEL repository
    dnf:
      name: epel-release
      state: present

  - name: Install Prometheus
    dnf:
      name: golang-github-prometheus
      state: present

  - name: Enable and start Prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
