---
  - name: Install nginx
    dnf:
      name: nginx
      state: present

  - name: Copy configuration file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - nginx_reload

  - name: Enable and start nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Configure firewall
    firewalld:
      port: 8080/tcp
      permanent: yes
      immediate: yes
      state: enabled

    # httpd_can_network_connect 0 Causes Bad Gateway error
  - name: Set SELinux boolean
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
